sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t argolpour/docker-react -f Dockerfile.dev .

script:
  - docker run  argolpour/docker-react npm run test -- --coverage
