sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t argolpour/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  argolpour/docker-react npm run test

